[build.environment]
PHP_VERSION = "8.2"

[build]
  command = "composer install && php artisan migrate --force && npm install"
  publish = "public"

[[redirects]]
from = "/app/*"
to = "/index.php"
status = 200
force = true


